name: Daniel Jongen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5286678
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4a4d56'
    - '#909baf'
    - '#757985'
    - '#0d0b0c'
    - '#be8a76'
  brandStrength: 0.625
  lightness: 0
  saturation: 0.5337268
  rhythmicContrast: 1
purpose: []
