layout_spectrum: 1
typography_spectrum: 0.5286678
color:
  saturation: 0.5337268
  lightness: 0
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: Daniel Jongen
